#!/bin/bash
clear
#                       _____               _  
#                      |  _  |             | | 
#   __ _ _ __ _ __ ___ | |/' | _ __ ___  __| | 
#  / _` | '__| '_ ` _ \|  /| || '__/ _ \/ _` | 
# | (_| | |  | | | | | \ |_/ /| | |  __/ (_| | 
#  \__,_|_|  |_| |_| |_|\___(_)_|  \___|\__,_| 

cat /usr/local/bin/arm0red
echo -e "\e[31;1m***** arm0.red Security *****\e[0m"
echo -e "\e[31;1m***** APT Update Script Running *****\e[0m"
sudo apt update && sudo apt full-upgrade -y
echo ""
echo -e "\e[1;32mDone.\e[0m"

