#!/bin/bash
clear
#                       _____               _  
#                      |  _  |             | | 
#   __ _ _ __ _ __ ___ | |/' | _ __ ___  __| | 
#  / _` | '__| '_ ` _ \|  /| || '__/ _ \/ _` | 
# | (_| | |  | | | | | \ |_/ /| | |  __/ (_| | 
#  \__,_|_|  |_| |_| |_|\___(_)_|  \___|\__,_| 

cat /usr/local/bin/arm0red
echo -e "\e[31;1m ***** \e[34;1m arm0.red Security \e[31;1m *****\e[0m"
echo -e "\e[31;1m ***** \e[34;1m Backup Script v2.0 \e[31;1m *****\e[0m"
echo ""

echo -e "\e[31;1m Enter \e[34;1m File/Directory\e[31;1m to be backed up:\e[0m"
read DIR

echo -e "\e[31;1m Enter\e[34;1m Output\e[31;1m Location:\e[0m"
read OL

IF=${DIR%}
echo -e "\e[31;1m *****  BACKING UP\e[34;1m $IF \e[31;1m *****\e[0m"
echo ""

OF=$OL/backup-$(hostname)-$(whoami)-${IF##*/}-$(date +%Y%m%d).tar.gz
tar --preserve-permissions -cvf - $IF | gzip -9 - > $OF

echo -e "\e[1;32mDone.\e[0m"


