#!/bin/bash
clear
#                       _____               _  
#                      |  _  |             | | 
#   __ _ _ __ _ __ ___ | |/' | _ __ ___  __| | 
#  / _` | '__| '_ ` _ \|  /| || '__/ _ \/ _` | 
# | (_| | |  | | | | | \ |_/ /| | |  __/ (_| | 
#  \__,_|_|  |_| |_| |_|\___(_)_|  \___|\__,_| 

cat /usr/local/bin/arm0red

sudo grubby --info=ALL | grep -E "^kernel|^index"

read -r -p "Which index number to you want to set as default? " response
sudo grubby --set-default-index=$response

sudo grubby --default-title
