#!/bin/bash
clear
#                       _____               _  
#                      |  _  |             | | 
#   __ _ _ __ _ __ ___ | |/' | _ __ ___  __| | 
#  / _` | '__| '_ ` _ \|  /| || '__/ _ \/ _` | 
# | (_| | |  | | | | | \ |_/ /| | |  __/ (_| | 
#  \__,_|_|  |_| |_| |_|\___(_)_|  \___|\__,_| 

cat /usr/local/bin/arm0red
echo -e "\e[31;1m ***** \e[34;1m arm0.red Security \e[31;1m *****\e[0m"
echo -e "\e[31;1m ***** \e[34;1m Kali Post Install v1.3 \e[31;1m *****\e[0m"

echo -e "\e[31;1m ***** \e[34;1m ADDING APT HTTPS SUPPORT \e[31;1m *****\e[0m"
sudo apt install apt-transport-https
sudo sed -i 's/http\:\/\//https\:\/\//g' /etc/apt/sources.list
echo ""

echo  -e "\e[31;1m ***** \e[34;1m UPDATING APT PACKAGES \e[31;1m *****\e[0m"
sudo apt update && sudo apt full-upgrade -y
echo ""

echo -e "\e[31;1m ***** INSTALLING \e[34;1m VEIL \e[31;1m *****\e[0m"
sudo apt -y install veil
sudo /usr/share/veil/config/setup.sh --force --silent
echo ""

echo -e "\e[31;1m ***** INSTALLING \e[34;1m Speedtest-cli \e[31;1m *****\e[0m"
sudo apt install speedtest-cli -y
echo ""

echo -e "\e[31;1m ***** INSTALLING \e[34;1m TOR \e[31;1m *****\e[0m"
sudo apt install tor torbrowser-launcher -y
echo ""

echo -e "\e[31;1m ***** INSTALLING \e[34;1m Kali-AnonSurf \e[31;1m by \e[34;1m Und3rf10w \e[31;1m *****\e[0m"
sudo apt install git -y
git clone https://github.com/Und3rf10w/kali-anonsurf.git
cd kali-anonsurf
sudo ./installer.sh
echo ""

echo -e "\e[31;1m ***** CHANGING DEFAULT \e[34;1m SSH KEYS \e[31;1m *****\e[0m"
sudo mkdir /etc/ssh/default_kali_keys
sudo mv /etc/ssh/ssh_host_* default_kali_keys/
sudo dpkg-reconfigure openssh-server
echo "Old Keys:"
sudo md5sum /etc/ssh/default_kali_keys/*
echo "New Keys:"
sudo md5sum /etc/ssh/*
echo ""

echo -e "\e[31;1m ***** SETTING UP \e[34;1m METASPLOIT DATABASE \e[31;1m *****\e[0m"
sudo systemctl start postgresql
sudo msfdb init
echo ""

# 64-Bit Keybase
echo -e "\e[31;1m ***** INSTALLING \e[34;1m KEYBASE \e[31;1m *****\e[0m"
curl -O https://prerelease.keybase.io/keybase_amd64.deb
# if you see an error about missing `libappindicator1`
# from the next command, you can ignore it, as the
# subsequent command corrects it
sudo dpkg -i keybase_amd64.deb
sudo apt-get install -f
run_keybase
echo ""

# 32-Bit Keybase
#echo -e "\e[31;1m ***** INSTALLING \e[34;1m KEYBASE \e[31;1m *****\e[0m"
#curl -O https://prerelease.keybase.io/keybase_i386.deb
# if you see an error about missing `libappindicator1`
# from the next command, you can ignore it, as the
# subsequent command corrects it
#sudo dpkg -i keybase_i386.deb
#sudo apt-get install -f
#run_keybase
#echo ""

echo -e "\e[31;1m ***** \e[34;1m Private Internet Access VPN is recommended \e[31;1m *****\e[0m"
echo -e "\e[31;1m ***** You can Download it at \e[34;1m https://www.privateinternetaccess.com/pages/pia-2yr-deal/arm0red \e[31;1m *****\e[0m"
#echo -e "\e[31;1m ***** \e[34;1m INSTALLING PRIVATE INTERNET ACCESS \e[31;1m *****\e[0m"
#cd Downloads
#tar -xzf pia-*-installer-linux.tar.gz
#./pia-*-installer-linux.sh
#cd ..
#echo ""

echo -e "\e[31;1mDon't forget to \e[34;1m REBOOT! \e[0m"
echo ""
echo -e "\e[1;32mDone.\e[0m"
