#!/bin/bash
clear
#                       _____               _  
#                      |  _  |             | | 
#   __ _ _ __ _ __ ___ | |/' | _ __ ___  __| | 
#  / _` | '__| '_ ` _ \|  /| || '__/ _ \/ _` | 
# | (_| | |  | | | | | \ |_/ /| | |  __/ (_| | 
#  \__,_|_|  |_| |_| |_|\___(_)_|  \___|\__,_| 

cat /usr/local/bin/arm0red
echo -e "\e[31;1m***** arm0.red Security *****\e[0m"
echo -e "\e[31;1m***** Arch Update Script Running *****\e[0m"

read -r -p "Do you want to check AUR for updates? [y/N] " response
if [[ $response =~ ^([Yy][eE][sS]|[yY])+$ ]]
then
    # This is for yay AUR update
    yay -Syu
    
    # This is for pacaur AUR update
    #pacaur -Syu -a
    
    # This is for yaourt AUR update
    #yaourt -Syu --aur
    
    # This is for paru AUR update
    #paru -Syu
    
else [[ $response =~ ^([N])+$ ]]
then
    # This is for regular pacman update
    sudo pacman -Syu
fi
echo ""
echo -e "\e[1;32mDone.\e[0m"

