#!/bin/bash
clear
#                       _____               _  
#                      |  _  |             | | 
#   __ _ _ __ _ __ ___ | |/' | _ __ ___  __| | 
#  / _` | '__| '_ ` _ \|  /| || '__/ _ \/ _` | 
# | (_| | |  | | | | | \ |_/ /| | |  __/ (_| | 
#  \__,_|_|  |_| |_| |_|\___(_)_|  \___|\__,_| 

cat arm0red
echo -e "\e[31;1m***** arm0.red Security *****\e[0m"
echo -e "\e[31;1m***** Pacman Update Script Running *****\e[0m"

# This is for regular pacman update
sudo pacman -Syu

# This is for pacaur AUR update
#pacaur -Syu -a

# This is for yaourt AUR update
#yaourt -Syu --aur

echo ""
echo -e "\e[1;32mDone.\e[0m"

