#!/bin/bash
clear
#                       _____               _  
#                      |  _  |             | | 
#   __ _ _ __ _ __ ___ | |/' | _ __ ___  __| | 
#  / _` | '__| '_ ` _ \|  /| || '__/ _ \/ _` | 
# | (_| | |  | | | | | \ |_/ /| | |  __/ (_| | 
#  \__,_|_|  |_| |_| |_|\___(_)_|  \___|\__,_| 

cat /usr/local/bin/arm0red
echo -e "\e[31;1m ***** \e[34;1m arm0.red Security \e[31;1m *****\e[0m"
echo -e "\e[31;1m ***** \e[34;1m System Info v2.0 \e[31;1m *****\e[0m"
echo ""

# This script will return the following set of system information:

# Hostname information:
echo -e "\e[31;1m ***** \e[34;1m HOSTNAME INFORMATION \e[31;1m *****\e[0m"
hostnamectl

# File system disk space usage:
echo -e "\e[31;1m ***** \e[34;1m FILE SYSTEM DISK SPACE USAGE \e[31;1m *****\e[0m"
df -h

# Free and used memory in the system:
echo -e "\e[31;1m ***** \e[34;1m FREE AND USED MEMORY \e[31;1m *****\e[0m"
free -h

# System uptime and load:
echo -e "\e[31;1m ***** \e[34;1m SYSTEM UPTIME AND LOAD \e[31;1m *****\e[0m"
uptime

# Logged-in users:
echo -e "\e[31;1m ***** \e[34;1m CURRENTLY LOGGED-IN USERS \e[31;1m *****\e[0m"
who

# Top 5 processes as far as memory usage is concerned
echo -e "\e[31;1m ***** \e[34;1m TOP 5 MEMORY-CONSUMING PROCESSES \e[31;1m *****\e[0m"
ps -eo %mem,%cpu,comm --sort=-%mem | head -n 6

# Default Gateway
echo -e "\e[31;1m ***** \e[34;1m Default Gateway \e[31;1m *****\e[0m"
route -n | grep 'UG[ \t]' | awk '{print $2}'

# Private IP
echo -e "\e[31;1m ***** \e[34;1m Private IP \e[31;1m *****\e[0m"
ifconfig | grep 'inet' | grep -v '127.0.0.1' | cut -d: -f2 | awk '{print $2}'

# Public IP
echo -e "\e[31;1m ***** \e[34;1m Public IP \e[31;1m *****\e[0m"
curl ifconfig.co
echo ""
echo -e "\e[1;32mDone.\e[0m"


