#!/bin/bash
clear
#                       _____               _  
#                      |  _  |             | | 
#   __ _ _ __ _ __ ___ | |/' | _ __ ___  __| | 
#  / _` | '__| '_ ` _ \|  /| || '__/ _ \/ _` | 
# | (_| | |  | | | | | \ |_/ /| | |  __/ (_| | 
#  \__,_|_|  |_| |_| |_|\___(_)_|  \___|\__,_| 

cat /usr/local/bin/arm0red
echo -e "\e[31;1m ***** \e[34;1m arm0.red Security \e[31;1m *****\e[0m"
echo -e "\e[31;1m ***** \e[34;1m wlan1 Monitor Mode \e[31;1m *****\e[0m"
echo ""

echo "Setting up wlan1 Monitor Mode."

ip link set wlan1 down
iw dev wlan1 set type monitor
#iw wlan1 set txpower fixed 3000
macchanger -r wlan1
ip link set wlan1 up

echo "Done."
