#!/bin/bash
clear
#                       _____               _  
#                      |  _  |             | | 
#   __ _ _ __ _ __ ___ | |/' | _ __ ___  __| | 
#  / _` | '__| '_ ` _ \|  /| || '__/ _ \/ _` | 
# | (_| | |  | | | | | \ |_/ /| | |  __/ (_| | 
#  \__,_|_|  |_| |_| |_|\___(_)_|  \___|\__,_| 

cat /usr/local/bin/arm0red
echo -e "\e[31;1m ***** \e[34;1m arm0.red Security \e[31;1m *****\e[0m"
echo -e "\e[31;1m ***** \e[34;1m Monitor Mode v1.3 \e[31;1m *****\e[0m"
echo ""

echo -e "\e[31;1m ***** Setting up \e[34;1m Monitor Mode \e[31;1m on \e34;1m wlan1 \e[31;1m *****\e[0m"

sudo ip link set wlan1 down
sudo iw dev wlan1 set type monitor
#sudo iw wlan1 set txpower fixed 3000
echo -e "\e[31;1m ***** Changing \e[34;1m Mac Address \e[31;1m on \e34;1m wlan1 \e[31;1m *****\e[0m"
sudo macchanger -r wlan1
sudo ip link set wlan1 up
sudo airmon-ng check kill
sudo iw dev wlan1 info
echo -e "\e[31;1m ***** \e34;1m wlan1 \e31;1m is now in \e[34;1m Monitor Mode \e[31;1m *****\e[0m"
echo -e "\e[1;32mDone.\e[0m"
